[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "build"
  port = 8888
  targetPort = 3000
  
[context.production.environment]
  URL = "http://brunaeeloan.com.br/"