// Lista de presentes para casamento
export const weddingGifts = [
  {
    id: 1,
    name: '2 Passagens Aéreas para a Lua de Mel',
    image: '/assets/casamento/presentes/lua_de_mel_passagem.png',
    price: 1560.71,
    category: 'Lua de Mel',
  },
  {
    id: 2,
    name: 'Abajur Decorativo',
    image: '/assets/casamento/presentes/abajur.png',
    price: 192.49,
    category: 'Decoração',
  },
  {
    id: 3,
    name: 'Adega de Vinhos Climatizada',
    image: '/assets/casamento/presentes/adega.png',
    price: 1248.57,
    category: 'Eletrodomésticos',
  },
  {
    id: 4,
    name: 'Aluguel de Carro para a Lua de Mel',
    image: '/assets/casamento/presentes/aluguel_carro.png',
    price: 1508.69,
    category: 'Lua de Mel',
  },
  {
    id: 6,
    name: 'Aparelho de Fondue Preto',
    image: '/assets/casamento/presentes/fondue.png',
    price: 114.45,
    category: 'Utilidades Domésticas',
  },
  {
    id: 7,
    name: 'Aparelho de Jantar Branco - 30 Peças',
    image: '/assets/casamento/presentes/aparelho_jantar.png',
    price: 1,
    category: 'Utilidades Domésticas',
  },
  {
    id: 8,
    name: 'Ar Condicionado Split Inverter 12000 BTUs',
    image: '/assets/casamento/presentes/ar_condicionado.png',
    price: 1975.86,
    category: 'Eletrodomésticos',
  },
  {
    id: 9,
    name: 'Aspirador de Pó Vertical',
    image: '/assets/casamento/presentes/aspirador.png',
    price: 182.08,
    category: 'Eletrodomésticos',
  },
  {
    id: 10,
    name: 'Bandeja Preta com Detalhe em Pesponto',
    image: '/assets/casamento/presentes/bandeja.png',
    price: 286.13,
    category: 'Utilidades Domésticas',
  },
  {
    id: 11,
    name: 'Batedeira Planetária',
    image: '/assets/casamento/presentes/batedeira.png',
    price: 515.03,
    category: 'Eletrodomésticos',
  },
  {
    id: 13,
    name: 'Buffet 4 Portas cor Madeira Natural e Azul',
    image: '/assets/casamento/presentes/buffet.png',
    price: 1300.59,
    category: 'Móveis',
  },
  {
    id: 14,
    name: 'Caixa Organizadora Trama com Tampa 40 x 30 cm',
    image: '/assets/casamento/presentes/caixa_organizadora.png',
    price: 197.69,
    category: 'Utilidades Domésticas',
  },
  {
    id: 15,
    name: 'Carrinho Gourmet para Churrasco',
    image: '/assets/casamento/presentes/carrinho_churrasco.png',
    price: 580.9,
    category: 'Utilidades Domésticas',
  },
  {
    id: 16,
    name: 'Centrifuga de Suco com Jarra',
    image: '/assets/casamento/presentes/centrifuga.png',
    price: 220.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 17,
    name: 'Churrasqueira Elétrica',
    image: '/assets/casamento/presentes/churrasqueira.png',
    price: 222.55,
    category: 'Eletrodomésticos',
  },
  {
    id: 19,
    name: 'Conjunto 2 Cadeiras Estofadas cor Areia',
    image: '/assets/casamento/presentes/cadeiras.png',
    price: 426.59,
    category: 'Móveis',
  },
  {
    id: 21,
    name: 'Conjunto de Mesas Laterais',
    image: '/assets/casamento/presentes/mesas_laterais.png',
    price: 335.84,
    category: 'Móveis',
  },
  {
    id: 22,
    name: 'Cooktop a Gás com Quatro Bocas',
    image: '/assets/casamento/presentes/cooktop.png',
    price: 1435.85,
    category: 'Eletrodomésticos',
  },
  {
    id: 23,
    name: 'Cortador de Pizza com Cabo de Bambu',
    image: '/assets/casamento/presentes/cortador_pizza.png',
    price: 119.1,
    category: 'Utilidades Domésticas',
  },
  {
    id: 24,
    name: 'Cota Jantar Romântico para o Casal',
    image: '/assets/casamento/presentes/jantar_romantico.png',
    price: 218.5,
    category: 'Experiências',
  },
  {
    id: 25,
    name: 'Cômoda Vermelha com 3 Gavetas',
    image: '/assets/casamento/presentes/comoda.png',
    price: 709.99,
    category: 'Móveis',
  },
  {
    id: 26,
    name: 'Decanter Vidro 1,25ml',
    image: '/assets/casamento/presentes/decanter.png',
    price: 114.45,
    category: 'Utilidades Domésticas',
  },
  {
    id: 27,
    name: 'Escorredor de Pratos Dobrável em Bambu',
    image: '/assets/casamento/presentes/escorredor.png',
    price: 161.27,
    category: 'Utilidades Domésticas',
  },
  {
    id: 28,
    name: 'Escrivaninha Branca com Gaveta',
    image: '/assets/casamento/presentes/escrivaninha.png',
    price: 420.35,
    category: 'Móveis',
  },
  {
    id: 29,
    name: 'Espelho Redondo 40 cm com Alça em Couro',
    image: '/assets/casamento/presentes/espelho.png',
    price: 275.72,
    category: 'Decoração',
  },
  {
    id: 31,
    name: 'Faqueiro - 42 Peças',
    image: '/assets/casamento/presentes/faqueiro.png',
    price: 269.48,
    category: 'Utilidades Domésticas',
  },
  {
    id: 32,
    name: 'Ferro de Passar a Vapor',
    image: '/assets/casamento/presentes/ferro.png',
    price: 59.31,
    category: 'Eletrodomésticos',
  },
  {
    id: 33,
    name: 'Forno de Embutir Elétrico 47 litros com Timer',
    image: '/assets/casamento/presentes/forno_embutir.png',
    price: 827.18,
    category: 'Eletrodomésticos',
  },
  {
    id: 35,
    name: 'Frigideira Antiaderente',
    image: '/assets/casamento/presentes/frigideira.png',
    price: 132.6,
    category: 'Utilidades Domésticas',
  },
  {
    id: 36,
    name: 'Fritadeira Air Fryer 3,2 litros',
    image: '/assets/casamento/presentes/airfryer.png',
    price: 293.41,
    category: 'Eletrodomésticos',
  },
  {
    id: 37,
    name: 'Geladeira Frost Free French Door 3 Portas 220V',
    image: '/assets/casamento/presentes/geladeira.png',
    price: 4369.99,
    category: 'Eletrodomésticos',
  },
  {
    id: 38,
    name: 'Home Theater Wireless',
    image: '/assets/casamento/presentes/home_theater.png',
    price: 551.45,
    category: 'Eletrônicos',
  },
  {
    id: 39,
    name: 'Jogo de Cama Listrado',
    image: '/assets/casamento/presentes/jogo_cama.png',
    price: 412.5,
    category: 'Cama, Mesa e Banho',
  },
  {
    id: 41,
    name: 'Jogo de Facas com Suporte em Madeira - 7 peças',
    image: '/assets/casamento/presentes/facas_7.png',
    price: 369.37,
    category: 'Utilidades Domésticas',
  },
  {
    id: 42,
    name: 'Jogo de Panelas Preto - 5 Peças',
    image: '/assets/casamento/presentes/panelas.png',
    price: 717.93,
    category: 'Utilidades Domésticas',
  },
  {
    id: 43,
    name: 'Jogo de Taças de Cristal - 6 Peças',
    image: '/assets/casamento/presentes/tacas.png',
    price: 181.3,
    category: 'Utilidades Domésticas',
  },
  {
    id: 45,
    name: 'Jogo de Vasos em Cerâmica',
    image: '/assets/casamento/presentes/vasos.png',
    price: 356.88,
    category: 'Decoração',
  },
  {
    id: 46,
    name: 'Jogo de Xícaras para Café com Pires - 12 peças',
    image: '/assets/casamento/presentes/xicaras.png',
    price: 243.95,
    category: 'Utilidades Domésticas',
  },
  {
    id: 47,
    name: 'Jogo Edredom Casal Cinza - 3 Peças',
    image: '/assets/casamento/presentes/edredom.png',
    price: 568.21,
    category: 'Cama, Mesa e Banho',
  },
  {
    id: 48,
    name: 'Jogo Toalha de Banho Azul - 4 Peças',
    image: '/assets/casamento/presentes/toalhas.png',
    price: 126.45,
    category: 'Cama, Mesa e Banho',
  },
  {
    id: 50,
    name: 'Lanterna Decorativa Boho em Bambu',
    image: '/assets/casamento/presentes/lanterna.png',
    price: 249.71,
    category: 'Decoração',
  },
  {
    id: 51,
    name: 'Lava Louças em Inox 14 Serviços',
    image: '/assets/casamento/presentes/lava_loucas.png',
    price: 3527.21,
    category: 'Eletrodomésticos',
  },
  {
    id: 52,
    name: 'Lixeira Inox 3 litros',
    image: '/assets/casamento/presentes/lixeira.png',
    price: 105.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 53,
    name: 'Manta Tricot Cinza 125cm x 150cm',
    image: '/assets/casamento/presentes/manta.png',
    price: 236.94,
    category: 'Cama, Mesa e Banho',
  },
  {
    id: 54,
    name: 'Maquina de Macarrão e Massas Caseira',
    image: '/assets/casamento/presentes/maquina_macarrao.png',
    price: 197.69,
    category: 'Eletrodomésticos',
  },
  {
    id: 55,
    name: 'Mesa de Centro Retangular Retrô Bege/Madeira',
    image: '/assets/casamento/presentes/mesa_centro.png',
    price: 171.68,
    category: 'Móveis',
  },
  {
    id: 56,
    name: 'Pipoqueira Elétrica sem Óleo',
    image: '/assets/casamento/presentes/pipoqueira.png',
    price: 149.99,
    category: 'Eletrodomésticos',
  },
  {
    id: 57,
    name: 'Processador de Alimentos Preto - 800W',
    image: '/assets/casamento/presentes/processador.png',
    price: 299.99,
    category: 'Eletrodomésticos',
  },
];

export default weddingGifts;
