// Lista de presentes para casamento ajustada
export const weddingGifts = [
  {
    id: 1,
    name: '2 Passagens Aéreas para a Lua de Mel',
    image: '/assets/casamento/presentes/lua_de_mel_passagem.png',
    price: 0.1,
    category: 'Lua de Mel',
  },
  {
    id: 2,
    name: 'Abajur Decorativo',
    image: '/assets/casamento/presentes/abajur.png',
    price: 0.5,
    category: 'Decoração',
  },
  {
    id: 3,
    name: 'Adega de Vinhos Climatizada',
    image: '/assets/casamento/presentes/adega.png',
    price: 1.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 4,
    name: 'Aluguel de Carro para a Lua de Mel',
    image: '/assets/casamento/presentes/aluguel_carro.png',
    price: 10.0,
    category: 'Lua de Mel',
  },
  {
    id: 6,
    name: 'Aparelho de Fondue Preto',
    image: '/assets/casamento/presentes/fondue.png',
    price: 155.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 7,
    name: 'Aparelho de Jantar Branco - 30 Peças',
    image: '/assets/casamento/presentes/aparelho_jantar.png',
    price: 350.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 8,
    name: 'Ar Condicionado Split Inverter 12000 BTUs',
    image: '/assets/casamento/presentes/ar_condicionado.png',
    price: 1980.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 9,
    name: 'Aspirador de Pó Vertical',
    image: '/assets/casamento/presentes/aspirador.png',
    price: 180.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 10,
    name: 'Bandeja Preta com Detalhe em Pesponto',
    image: '/assets/casamento/presentes/bandeja.png',
    price: 285.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 11,
    name: 'Batedeira Planetária',
    image: '/assets/casamento/presentes/batedeira.png',
    price: 515.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 13,
    name: 'Buffet 4 Portas cor Madeira Natural e Azul',
    image: '/assets/casamento/presentes/buffet.png',
    price: 1300.0,
    category: 'Móveis',
  },
  {
    id: 14,
    name: 'Caixa Organizadora Trama com Tampa 40 x 30 cm',
    image: '/assets/casamento/presentes/caixa_organizadora.png',
    price: 200.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 15,
    name: 'Carrinho Gourmet para Churrasco',
    image: '/assets/casamento/presentes/carrinho_churrasco.png',
    price: 580.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 16,
    name: 'Centrifuga de Suco com Jarra',
    image: '/assets/casamento/presentes/centrifuga.png',
    price: 220.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 17,
    name: 'Churrasqueira Elétrica',
    image: '/assets/casamento/presentes/churrasqueira.png',
    price: 225.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 19,
    name: 'Conjunto 2 Cadeiras Estofadas cor Areia',
    image: '/assets/casamento/presentes/cadeiras.png',
    price: 425.0,
    category: 'Móveis',
  },
  {
    id: 21,
    name: 'Conjunto de Mesas Laterais',
    image: '/assets/casamento/presentes/mesas_laterais.png',
    price: 335.0,
    category: 'Móveis',
  },
  {
    id: 22,
    name: 'Cooktop a Gás com Quatro Bocas',
    image: '/assets/casamento/presentes/cooktop.png',
    price: 1440.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 24,
    name: 'Cota Jantar Romântico para o Casal',
    image: '/assets/casamento/presentes/jantar_romantico.png',
    price: 220.0,
    category: 'Experiências',
  },
  {
    id: 25,
    name: 'Cômoda Vermelha com 3 Gavetas',
    image: '/assets/casamento/presentes/comoda.png',
    price: 710.0,
    category: 'Móveis',
  },
  {
    id: 26,
    name: 'Decanter Vidro 1,25ml',
    image: '/assets/casamento/presentes/decanter.png',
    price: 150.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 27,
    name: 'Escorredor de Pratos Dobrável em Bambu',
    image: '/assets/casamento/presentes/escorredor.png',
    price: 160.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 28,
    name: 'Escrivaninha Branca com Gaveta',
    image: '/assets/casamento/presentes/escrivaninha.png',
    price: 420.0,
    category: 'Móveis',
  },
  {
    id: 29,
    name: 'Espelho Redondo 40 cm com Alça em Couro',
    image: '/assets/casamento/presentes/espelho.png',
    price: 275.0,
    category: 'Decoração',
  },
  {
    id: 31,
    name: 'Faqueiro - 42 Peças',
    image: '/assets/casamento/presentes/faqueiro.png',
    price: 270.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 32,
    name: 'Ferro de Passar a Vapor',
    image: '/assets/casamento/presentes/ferro.png',
    price: 210.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 33,
    name: 'Forno de Embutir Elétrico 47 litros com Timer',
    image: '/assets/casamento/presentes/forno_embutir.png',
    price: 830.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 35,
    name: 'Frigideira Antiaderente',
    image: '/assets/casamento/presentes/frigideira.png',
    price: 220.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 36,
    name: 'Fritadeira Air Fryer 3,2 litros',
    image: '/assets/casamento/presentes/airfryer.png',
    price: 320.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 37,
    name: 'Geladeira Frost Free French Door 3 Portas 220V',
    image: '/assets/casamento/presentes/geladeira.png',
    price: 4370.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 38,
    name: 'Home Theater Wireless',
    image: '/assets/casamento/presentes/home_theater.png',
    price: 550.0,
    category: 'Eletrônicos',
  },
  {
    id: 39,
    name: 'Jogo de Cama Listrado',
    image: '/assets/casamento/presentes/jogo_cama.png',
    price: 410.0,
    category: 'Cama, Mesa e Banho',
  },
  {
    id: 41,
    name: 'Jogo de Facas com Suporte em Madeira - 7 peças',
    image: '/assets/casamento/presentes/facas_7.png',
    price: 370.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 42,
    name: 'Jogo de Panelas Preto - 5 Peças',
    image: '/assets/casamento/presentes/panelas.png',
    price: 720.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 43,
    name: 'Jogo de Taças de Cristal - 6 Peças',
    image: '/assets/casamento/presentes/tacas.png',
    price: 240.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 45,
    name: 'Jogo de Vasos em Cerâmica',
    image: '/assets/casamento/presentes/vasos.png',
    price: 355.0,
    category: 'Decoração',
  },
  {
    id: 46,
    name: 'Jogo de Xícaras para Café com Pires - 12 peças',
    image: '/assets/casamento/presentes/xicaras.png',
    price: 245.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 47,
    name: 'Jogo Edredom Casal Cinza - 3 Peças',
    image: '/assets/casamento/presentes/edredom.png',
    price: 570.0,
    category: 'Cama, Mesa e Banho',
  },
  {
    id: 48,
    name: 'Jogo Toalha de Banho Azul - 4 Peças',
    image: '/assets/casamento/presentes/toalhas.png',
    price: 150.0,
    category: 'Cama, Mesa e Banho',
  },
  {
    id: 50,
    name: 'Lanterna Decorativa Boho em Bambu',
    image: '/assets/casamento/presentes/lanterna.png',
    price: 250.0,
    category: 'Decoração',
  },
  {
    id: 51,
    name: 'Lava Louças em Inox 14 Serviços',
    image: '/assets/casamento/presentes/lava_loucas.png',
    price: 3530.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 52,
    name: 'Lixeira Inox 3 litros',
    image: '/assets/casamento/presentes/lixeira.png',
    price: 150.0,
    category: 'Utilidades Domésticas',
  },
  {
    id: 53,
    name: 'Manta Tricot Cinza 125cm x 150cm',
    image: '/assets/casamento/presentes/manta.png',
    price: 235.0,
    category: 'Cama, Mesa e Banho',
  },
  {
    id: 54,
    name: 'Maquina de Macarrão e Massas Caseira',
    image: '/assets/casamento/presentes/maquina_macarrao.png',
    price: 200.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 55,
    name: 'Mesa de Centro Retangular Retrô Bege/Madeira',
    image: '/assets/casamento/presentes/mesa_centro.png',
    price: 170.0,
    category: 'Móveis',
  },
  {
    id: 56,
    name: 'Pipoqueira Elétrica sem Óleo',
    image: '/assets/casamento/presentes/pipoqueira.png',
    price: 150.0,
    category: 'Eletrodomésticos',
  },
  {
    id: 57,
    name: 'Processador de Alimentos Preto - 800W',
    image: '/assets/casamento/presentes/processador.png',
    price: 300.0,
    category: 'Eletrodomésticos',
  },
];

export default weddingGifts;
